### ISSUE TITLE
edit message

### ISSUE THREAD

**Issue by hell4opt** [ShaneQi/ZEGBot#5]
hi! can u add opportunity to edit message

**Comment by ShaneQi** [comment]
Sure, I can look into that tonight.

**Comment by hell4opt** [comment]
> Sure, I can look into that tonight.

thanks for the quick reply) since you are here, can you somehow find out how many photos came in the message? now every photo is a different message to the bot, but how many of them came to understand is unrealistic, just set a timer and hopes for 5 seconds to process everything)

**Comment by ShaneQi** [comment]
If you are talking about when multiple photos are sent in one-go (shown as a grid album in the app), yes there is a way to know that:

Even though the photos of this album/group are in different `Message` objects, all the `Message` objects of the photos will have the same `mediaGroupId `. But here are the things not yet in this library (ZEGBot):

1. `mediaGroupId` hasn't been added into `Message` object.
2. Right now you can only give handler of ONE update (containing only one message) to `ZEGBot`, in this handler you don't know if there are more updates/messages are related (for example multiple updates/messages are in the same media group).

**I will fix these two issues** (probably tonight along with the edit message feature) by adding `mediaGroupId` to `Message` object as well as adding a new method to accept handler of multiple updates, so that you can simply pick out all the messages with the same `mediaGroupId` from updates to know how many photos were sent together.

Hope this makes sense to you.

**Comment by hell4opt** [comment]
> If you are talking about when multiple photos are sent in one-go (shown as a grid album in the app), yes there is a way to know that:
> 
> Even though the photos of this album/group are in different `Message` objects, all the `Message` objects of the photos will have the same `mediaGroupId`. But here are the things not yet in this library (ZEGBot):
> 
> 1. `mediaGroupId` hasn't been added into `Message` object.
> 2. Right now you can only give handler of ONE update (containing only one message) to `ZEGBot`, in this handler you don't know if there are more updates/messages that are related to this update/message (for example multiple updates/messages are related to the same media group).
> 
> **I will fix these two issues** (probably tonight along with the edit message feature) by adding `mediaGroupId` to `Message` object as well as adding a new method to accept handler of multiple updates, so that you can simply pick out all the messages with the same `mediaGroupId` from updates to know how many photos were sent together.
> 
> Hope this makes sense to you.

thx man!! where i can donate?)

**Comment by ShaneQi** [comment]
No donation needed : )

If you have the capacity (only if you do) you can make changes to `ZEGBot` so that you have what you need instantly and you can submit PRs so that everyone else has it. The library is really not that complicated.

**Comment by hell4opt** [comment]
wow! i really want donate :)

No, i am noobie :) (junior)

**Comment by ShaneQi** [comment]
Changed are done, make sure you are using the new version:

`.package(url: "https://github.com/shaneqi/ZEGBot.git", from: Version(4, 2, 3))`

Then you will be able to know grouped photos, for example:

```swift
let bot = ZEGBot(token: "TYPE YOUR TOKEN HERE")

// swiftlint:disable force_try
try! bot.run { updates, bot in
	let messages = updates.compactMap { $0.message }
	let groupedMessage = Dictionary(grouping: messages, by: { $0.mediaGroupId })
	for (mediaGroupId, messages) in groupedMessage {
		guard let mediaGroupId = mediaGroupId else {
			continue
		}
		print(mediaGroupId)
		// These messages/photos were sent as a group/album.
		dump(messages)
	}
}

```

**Comment by hell4opt** [comment]
> Changed are done, make sure you are using the new version:
> 
> `.package(url: "https://github.com/shaneqi/ZEGBot.git", from: Version(4, 2, 3))`
> 
> Then you will be able to know grouped photos, for example:
> 
> ```swift
> let bot = ZEGBot(token: "TYPE YOUR TOKEN HERE")
> 
> // swiftlint:disable force_try
> try! bot.run { updates, bot in
> 	let messages = updates.compactMap { $0.message }
> 	let groupedMessage = Dictionary(grouping: messages, by: { $0.mediaGroupId })
> 	for (mediaGroupId, messages) in groupedMessage {
> 		guard let mediaGroupId = mediaGroupId else {
> 			continue
> 		}
> 		print(mediaGroupId)
> 		// These messages/photos were sent as a group/album.
> 		dump(messages)
> 	}
> }
> ```

big big big thx!
